home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('contact/', Contact.as_view(), name='contact'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('adminpage/', include('adminpage.urls')),
    path('order/', include('order.urls')),
    path('product/', include('product.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'order'

urlpatterns = [
    path('add-to-cart/', AddToCart.as_view(), name='add-to-cart'),
    path('remove_item_in_cart/', RemoveItemToCart.as_view(), name='remove_item_in_cart'),
    path('shopping-cart/', CartView.as_view(), name='cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
]

product/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'product'

urlpatterns = [
    path('productdetail/<slug:slug>/', ProductDetail.as_view(), name='productdetail'),
    path('product/', ProductView.as_view(), name='product'),
    path('product/filter/<str:category>', ProductView.as_view(), name='productfilter'),
    path('product/search/', ProductSearch.as_view(), name='productsearch'),
]

templates/base/footer.html
{% load static %}
<footer class="bg-second">
    <div class="container">
        <div class="row">
            <div class="col-3 col-md-6">
                <h3 class="footer-head">Sản phẩm</h3>
                <ul class="menu">
                    <li><a href="#"><i class="fa-solid fa-book"></i>Tiểu thuyết</a></li>
                    <li><a href="#"><i class="fa-solid fa-book"></i>Tâm lý</a></li>
                    <li><a href="#"><i class="fa-solid fa-book"></i>Kinh dị</a></li>
                    <li><a href="#"><i class="fa-solid fa-book"></i>Truyện tranh</a></li>
                    <li><a href="#"><i class="fa-solid fa-book"></i>Tình cảm</a></li>
                </ul>
            </div>
            <div class="col-3 col-md-6">
                <h3 class="footer-head">Dịch vụ</h3>
                <ul class="menu">
                    <li><a href="#"><i class="fa-solid fa-ticket"></i>Khuyến mãi</a></li>
                    <li><a href="#"><i class="fa-solid fa-truck-fast"></i>Chính sách vận chuyển</a></li>
                    <li><a href="#"><i class="fa-solid fa-person"></i>Chính sách hỗ trợ khách hàng</a></li>
                    <li><a href="#"><i class="fa-solid fa-lock"></i>Chính sách bảo mật</a></li>
                </ul>
            </div>
            <div class="col-3 col-md-6">
                <h3 class="footer-head">Hỗ trợ</h3>
                <ul class="menu">
                    <li><a href="#"><i class="fa-solid fa-phone"></i>02871059999</a></li>
                    <li><a href="#"><i class="fa-solid fa-location-dot"></i>Cơ sở 1: 233A Phan Văn Trị, P.11, Q. Bình Thạnh, TP. HCM</a></li>
                    <li><a href="#"><i class="fa-solid fa-location-dot"></i>Cơ sở 2: 45 Nguyễn Khắc Nhu, P. Cô Giang, Q.1, TP. HCM</a></li>
                    <li><a href="#"><i class="fa-solid fa-location-dot"></i>Cơ sở 3: 69/68 Đặng Thùy Trâm, P. 13, Q. Bình Thạnh, TP. HCM</a></li>
                </ul>
            </div>
            <div class="col-3 col-md-6 col-sm-12">
                <div class="contact" style="transform: translateY(-3rem);">
                    <img src="{% static 'home/img/logoVLU.png' %}/" alt="">
                    <h3 class="contact-header">
                        LDStore
                    </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">Copyright LDStore since 2022</div>
</footer>

templates/base/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'user/img/logo.png' %}" type="image/png">
    <!-- google font -->    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@100&display=swap" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <!-- boxicons -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <!-- app css -->
    <link rel="stylesheet" href="{% static 'home/css/grid.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'home/css/app.css' %}" type="text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

templates/base/header.html
{% load static %}
   <!-- header -->
    <header>
        <!-- mobile menu -->
        <div class="mobile-menu bg-second">
            <a href="#" class="mb-logo">LDStore</a>
            <span class="mb-menu-toggle" id="mb-menu-toggle">
                <i class='bx bx-menu'></i>
            </span>
        </div>
        <!-- end mobile menu -->
        <!-- main header -->
        <div class="header-wrapper" id="header-wrapper">
            <span class="mb-menu-toggle mb-menu-close" id="mb-menu-close">
                <i class='bx bx-x'></i>
            </span>
            <!-- mid header -->
            <div class="bg-main">
                <div class="mid-header container">
                    <img src="{% static 'home/img/favicon3.png' %}" alt="">
                    <a href="{% url 'home:index' %}" class="logo">LDStore</a>
                    <div class="search">
                        <form method="post" action="{% url 'product:productsearch' %}">
                            {% csrf_token %}
                            <input name="user_search" type="text" placeholder="Tìm kiếm">
                            <button type="submit">
                                <i class='bx bx-search-alt'></i>
                            </button>
                        </form>
                    </div>
                    <ul class="user-menu">
                        <li><a href="{% url 'order:cart' %}">
                            <i class="fa fa-shopping-bag"></i>
                        </a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'signout' %}"><i class="fa-solid fa-arrow-right-from-bracket"></i></a></li>
                            <li><a href="{% url 'profile' %}"><i class="bx bx-cog"></i></a></li>
                            <p>Hi {{ request.user.username }}</p>
                        {% else %}
                            <li><a href="{% url 'signin' %}"><i class='bx bx-user-circle'></i></a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <!-- end mid header -->
            <!-- bottom header -->
            <div class="bg-second">
                <div class="bottom-header container">
                    <ul class="main-menu">
                        <li><a href="{% url 'home:index' %}">Trang chủ</a></li>
                        <!-- mega menu -->
                        <li class="mega-dropdown">
                            <a href="">Thể loại<i class='bx bxs-chevron-down'></i></a>
                            <div class="mega-content">
                                <div class="row">
                                    <div class="col-3 col-md-12">
                                        <div class="box">
                                            <ul>
                                                {% for category in categories %}
                                                <li><a href="{% url 'product:productfilter' category=category.title %}">{{ category.title }}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                            </div>
                        </li>
                        <!-- end mega menu -->
                        <li><a href="{% url 'home:contact' %}">Liên hệ</a></li>
                    </ul>
                </div>
            </div>
            <!-- end bottom header -->
        </div>
        <!-- end main header -->
    </header>
    <!-- end header -->

templates/base/js.html
{% load static %}

<script src="{% static 'home/js/app.js' %}"></script>
<script src="{% static 'home/js/index.js' %}"></script>