adminpage/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'adminpage'

urlpatterns = [
    path('usermanagement/', UserManagement.as_view(), name='usermanagement'),
    path('ordermanagement/', OrderManagement.as_view(), name='ordermanagement'),
    path('productmanagement/', ProductManagement.as_view(), name='productmanagement'),
    path('vouchermanagement/', VoucherManagement.as_view(), name='vouchermanagement'),
    path('statistic/', Statistic.as_view(), name='statistic'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('contact/', Contact.as_view(), name='contact'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('adminpage/', include('adminpage.urls')),
    path('order/', include('order.urls')),
    path('product/', include('product.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpage/models.py
from django.db import models

# Create your models here.

adminpage/views.py
from django.shortcuts import render
from django.views.generic import View

from user.models import CustomUser


# Create your views here.
class UserManagement(View):
    template_name = "adminpage/Manage-User.html"

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        context = {
            'users': users,
            'route': 'usermanagement'
        }
        return render(request, self.template_name, context)


class OrderManagement(View):
    template_name = "adminpage/Manage-Order.html"

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        context = {
            'users': users,
            'route': 'ordermanagement'
        }
        return render(request, self.template_name, context)


class ProductManagement(View):
    template_name = "adminpage/Manage-Product.html"

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        context = {
            'users': users,
            'route': 'productmanagement'
        }
        return render(request, self.template_name, context)


class VoucherManagement(View):
    template_name = "adminpage/Manage-Voucher.html"

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        context = {
            'users': users,
            'route': 'vouchermanagement'
        }
        return render(request, self.template_name, context)


class Statistic(View):
    template_name = "adminpage/Statistics.html"

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        context = {
            'users': users,
            'route': 'statistics'
        }
        return render(request, self.template_name, context)

adminpage/templates/adminpage/Manage-Order.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    {% include "adminpage/head.html" %}
</head>
<body>
    <div class="navbar">
		<!-- nav left -->
		<ul class="navbar-nav">
			
			<li class="nav-item">
				<img  src="{% static 'adminpage/img/logo.png' %}" alt="ATPro logo" class="logo logo-light">
				<img  src="{% static 'adminpage/img/logo.png' %}" alt="ATPro logo" class="logo logo-dark">
				<span style="font-size: 30px; font-weight: bold; transform: translateY(-20px); display: inline-block;">LDStore</span>
			</li>
		</ul>
		<!-- end nav left -->
		<!-- form -->
		<form class="navbar-search">
			<input type="text" name="Search" class="navbar-search-input" placeholder="What you looking for...">
			<i class="fas fa-search"></i>
		</form>
		<!-- end form -->
		<!-- nav right -->
		<ul class="navbar-nav nav-right">
			<li class="nav-item mode">
				<a class="nav-link" href="#" onclick="switchTheme()">
					<i class="fas fa-moon dark-icon"></i>
					<i class="fas fa-sun light-icon"></i>
				</a>
			</li>
			<!--  -->
			<li class="nav-item avt-wrapper">
				<div class="avt dropdown">
					<img src="assets/tuat.jpg" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
					<ul id="user-menu" class="dropdown-menu">
						<li  class="dropdown-menu-item">
							<a class="dropdown-menu-link">
								<div>
									<i class="fas fa-user-tie"></i>
								</div>
								<span>Profile</span>
							</a>
						</li>
						
						<li  class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-sign-out-alt"></i>
								</div>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
		<!-- end nav right -->
	</div>
	<!-- end navbar -->
	<!-- sidebar -->
    {% include "adminpage/sidebar.html" %}



	<!-- -------------------------------------bảng thông kê-------------------------------------- -->
	<div class="wrapper">
		<div class="table-manage">
			<div class="card">
				<div class="card-header">
					<h3 style="display: inline-block;">
						Quản Lý Đơn Hàng
					</h3>
					<a href="#" class="btn" style="float:right;">Thêm</a>
				</div>
				<div class="card-content">
					<table>
						<thead>
							<tr>
								<th>STT</th>
								<th>Mã Đơn Hàng</th>
								<th>Giá</th>
								<th>Tình Trạng Đơn Hàng</th>
								<th>Địa Chỉ Nhận Hàng</th>
                            	<th>Sửa</th>
								<th>Xóa</th>

							</tr>
						</thead>
						<tbody>
							<tr>
								<td>1</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>2</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>3</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>4</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>4</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>5</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>6</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>7</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>8</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>9</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>10</td>
								<td>MC1DR7K</td>
								<td>20000Đ</td>
								<td>Đang ở kho</td>
								<td>2/3/4/5/7/9 đường phạm văn đồng, Quận Thủ Đức, TP HCM</td>
                                <td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
	<script src="{% static 'adminpage/js/index.js' %}"></script>
</body>
</html>

adminpage/templates/adminpage/Manage-Product.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    {% include "adminpage/head.html" %}
</head>
<body>
    <div class="navbar">
		<!-- nav left -->
		<ul class="navbar-nav">
			
			<li class="nav-item">
				<img  src="{% static 'adminpage/img/logo.png' %}" alt="ATPro logo" class="logo logo-light">
				<img  src="{% static 'adminpage/img/logo.png' %}" alt="ATPro logo" class="logo logo-dark">
				<span style="font-size: 30px; font-weight: bold; transform: translateY(-20px); display: inline-block;">LDStore</span>
			</li>
		</ul>
		<!-- end nav left -->
		<!-- form -->
		<form class="navbar-search">
			<input type="text" name="Search" class="navbar-search-input" placeholder="What you looking for...">
			<i class="fas fa-search"></i>
		</form>
		<!-- end form -->
		<!-- nav right -->
		<ul class="navbar-nav nav-right">
			<li class="nav-item mode">
				<a class="nav-link" href="#" onclick="switchTheme()">
					<i class="fas fa-moon dark-icon"></i>
					<i class="fas fa-sun light-icon"></i>
				</a>
			</li>
			<!--  -->
			<li class="nav-item avt-wrapper">
				<div class="avt dropdown">
					<img src="assets/tuat.jpg" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
					<ul id="user-menu" class="dropdown-menu">
						<li  class="dropdown-menu-item">
							<a class="dropdown-menu-link">
								<div>
									<i class="fas fa-user-tie"></i>
								</div>
								<span>Profile</span>
							</a>
						</li>
						
						<li  class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-sign-out-alt"></i>
								</div>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
		<!-- end nav right -->
	</div>
	<!-- end navbar -->
	<!-- sidebar -->
    {% include "adminpage/sidebar.html" %}


    <!-- -------------------------------------bảng thông kê-------------------------------------- -->
	<div class="wrapper">
		<div class="table-manage">
			<div class="card">
				<div class="card-header">
					<h3>
						Quản Lý Sản Phẩm
					</h3>
					<i class="fas fa-ellipsis-h"></i>
				</div>
				<div class="card-content">
					<table>
						<thead>
							<tr>
								<th>STT</th>
								<th>Tên Sản Phẩm</th>
								<th>Giá</th>
								<th>Mô Tả</th>
								<th>Số Lượng</th>
                                <th>Tình Trạng</th>
                                <th>Số Lượng Đã Bán</th>
								<th>Sửa</th>
								<th>Xóa</th>

							</tr>
						</thead>
						<tbody>
							<tr>
								<td>1</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>2</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>2</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>3</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>4</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
							<tr>
								<td>5</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
                            <tr>
								<td>6</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
                            <tr>
								<td>7</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
                            <tr>
								<td>8</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
                            <tr>
								<td>9</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
                            <tr>
								<td>10</td>
								<td>React</td>
								<td>20000Đ</td>
								<td>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Culpa ipsa labore, ipsam dolore cumque eius veritatis dignissimos, similique, atque beatae ratione dicta soluta delectus autem quam eaque! Architecto, totam atque?</td>
								<td>1000 Cái</td>
                                <td>Còn Hàng</td>
                                <td>200 Cái</td>
								<td><a href="#" class="btn">Xóa</a> </td>
								<td><a href="#" class="btn">Sửa</a> </td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
	<script src="{% static 'adminpage/js/index.js' %}"></script>
</body>
</html>

adminpage/templates/adminpage/Manage-User.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    {% include "adminpage/head.html" %}
</head>

<body>
    <div class="navbar">
        <!-- nav left -->
        <ul class="navbar-nav">

            <li class="nav-item">
                <img  src="{% static 'adminpage/img/logo.png' %}" alt="ATPro logo" class="logo logo-light">
				<img  src="{% static 'adminpage/img/logo.png' %}" alt="ATPro logo" class="logo logo-dark">
				<span style="font-size: 30px; font-weight: bold; transform: translateY(-20px); display: inline-block;">LDStore</span>
            </li>
        </ul>
        <!-- end nav left -->
        <!-- form -->
        <form class="navbar-search">
            <input type="text" name="Search" class="navbar-search-input" placeholder="What you looking for...">
            <i class="fas fa-search"></i>
        </form>
        <!-- end form -->
        <!-- nav right -->
        <ul class="navbar-nav nav-right">
            <li class="nav-item mode">
                <a class="nav-link" href="#" onclick="switchTheme()">
                    <i class="fas fa-moon dark-icon"></i>
                    <i class="fas fa-sun light-icon"></i>
                </a>
            </li>
            <!--  -->
            <li class="nav-item avt-wrapper">
                <div class="avt dropdown">
                    <img src="assets/tuat.jpg" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
                    <ul id="user-menu" class="dropdown-menu">
                        <li class="dropdown-menu-item">
                            <a class="dropdown-menu-link">
                                <div>
                                    <i class="fas fa-user-tie"></i>
                                </div>
                                <span>Profile</span>
                            </a>
                        </li>

                        <li class="dropdown-menu-item">
                            <a href="#" class="dropdown-menu-link">
                                <div>
                                    <i class="fas fa-sign-out-alt"></i>
                                </div>
                                <span>Logout</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
        <!-- end nav right -->
    </div>
    <!-- end navbar -->
    <!-- sidebar -->
    {% include "adminpage/sidebar.html" %}


    <!-- -------------------------------------bảng thông kê-------------------------------------- -->
    <div class="wrapper">


        <div class="table-manage">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Quản Lý Người Dùng
                    </h3>
                    <i class="fas fa-ellipsis-h"></i>
                </div>
                <div class="card-content">
                    <table>
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Họ và Tên</th>
                                <th>Emal</th>
                                <th>Số Điện Thoại</th>
                                <th>Giới Tính</th>
                                <th>Xóa</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ user.fullname }}</td>
                                    <td>{{ user.email }}</td>
                                    <td>{{ user.phone_number }}</td>
                                    <td>{{ user.sex }}</td>
                                    <td><a href="#" class="btn">Xóa</a> </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    
    <script src="{% static 'adminpage/js/index.js' %}"></script>
</body>

</html>

adminpage/templates/adminpage/head.html
{% load static %}
<title>Admin</title>

    <meta name="viewport"
        content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
        <link rel="icon" type="image/png" href="{% static 'adminpage/img/logo.png' %}"/>

    <!-- Import lib -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css">
    <link rel="stylesheet" type="text/css" href="fontawesome-free/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- End import lib -->

    

    <link rel="stylesheet" type="text/css" href="{% static 'adminpage/css/style.css' %}">

adminpage/templates/adminpage/sidebar.html
<div class="sidebar">
    <ul class="sidebar-nav">
        <li class="sidebar-nav-item">
            <a href="{% url 'adminpage:statistic' %}" class="sidebar-nav-link {% if route == 'statistics' %}active{% endif %}">
                <div>
                    <i class="fa-solid fa-chart-simple"></i>
                </div>
                <span>Thông Kê</span>
            </a>
        </li>
        <li class="sidebar-nav-item">
            <a href="{% url 'adminpage:usermanagement' %}" class="sidebar-nav-link {% if route == 'usermanagement' %}active{% endif %}">
                <div>
                    <i class="fa-solid fa-person"></i>
                </div>
                <span>Người Dùng</span>
            </a>
        </li>
        <li class="sidebar-nav-item">
            <a href="{% url 'adminpage:productmanagement' %}" class="sidebar-nav-link {% if route == 'productmanagement' %}active{% endif %}">
                <div>
                    <i class="fa-solid fa-list"></i>
                </div>
                <span>Sản Phẩm</span>
            </a>
        </li>
        <li class="sidebar-nav-item">
            <a href="{% url 'adminpage:ordermanagement' %}" class="sidebar-nav-link {% if route == 'ordermanagement' %}active{% endif %}">
                <div>
                    <i class="fa-solid fa-basket-shopping"></i>
                </div>
                <span>Đơn Hàng</span>
            </a>
        </li>
        <li class="sidebar-nav-item">
            <a href="{% url 'adminpage:vouchermanagement' %}" class="sidebar-nav-link {% if route == 'vouchermanagement' %}active{% endif %}">
                <div>
                    <i class="fa-solid fa-ticket"></i>
                </div>
                <span>Khuyến Mãi</span>
            </a>
        </li>

    </ul>
</div>