home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('contact/', Contact.as_view(), name='contact'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('adminpage/', include('adminpage.urls')),
    path('order/', include('order.urls')),
    path('product/', include('product.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'order'

urlpatterns = [
    path('add-to-cart/', AddToCart.as_view(), name='add-to-cart'),
    path('remove_item_in_cart/', RemoveItemToCart.as_view(), name='remove_item_in_cart'),
    path('shopping-cart/', CartView.as_view(), name='cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
]

product/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'product'

urlpatterns = [
    path('productdetail/<slug:slug>/', ProductDetail.as_view(), name='productdetail'),
    path('product/', ProductView.as_view(), name='product'),
    path('product/filter/<str:category>', ProductView.as_view(), name='productfilter'),
    path('product/search/', ProductSearch.as_view(), name='productsearch'),
]

product/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.functional import cached_property

from .utils import remove_accents


# Create your models here.
class Category(models.Model):

    title = models.CharField(max_length=30)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to = 'images/categories/%Y-%m-%d/', blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def  __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.title) + "-" + str(self.id)
            self.save()


class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to = 'images/products/%Y-%m-%d/')
    price = models.FloatField()
    amount = models.IntegerField()
    avg_rating = models.IntegerField(null=True, blank=True, default=0)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    have_discount = models.BooleanField(default=False)
    discount_price = models.FloatField(blank=True, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.name) + "-" + str(self.id)
            self.save()

    def __str__(self):
        return self.name

    @property
    def search_name(self):
        return remove_accents(self.name)


class ProductSlider(models.Model):
    product = models.ManyToManyField(Product, related_name='productslider')

    def __str__(self) -> str:
        return "ProdcutSlider"

product/views.py
from django.shortcuts import render
from django.views.generic import View

from .models import Product, Category
from .utils import remove_accents


# Create your views here.
class ProductDetail(View):
    template_name = "product/product-detail.html"

    def get(self, request, *args, **kwargs):
        slug = kwargs.get("slug")
        product = Product.objects.filter(slug=slug).first()
        title = product.name
        context = {
            "product": product,
            "title": title
        }
        return render(request, self.template_name, context)


class ProductView(View):
    template_name = "product/products.html"

    def get(self, request, *args, **kwargs):

        products = Product.objects.all()
        categories = Category.objects.all()
        if kwargs.get("category"):
            category = Category.objects.filter(title=kwargs.get("category")).first()
            products = products.filter(category=category)
        context = {
            "products": products,
            "title": "Products",
            "categories": categories,
        }
        return render(request, self.template_name, context)


class ProductSearch(View):
    template_name = "product/products.html"

    def post(self, request, *args, **kwargs):

        products = Product.objects.all()
        categories = Category.objects.all()
        user_search = request.POST.get('user_search')
        if user_search:
            user_search = remove_accents(user_search)
            products = [x for x in products if user_search in x.search_name]

        context = {
            "products": products,
            "title": "Products",
            "categories": categories
        }
        return render(request, self.template_name, context)

product/templates/product/products.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
    {% include "base/head.html" %}
</head>

<body>

    <!-- header -->
    {% include "base/header.html" %}
    <!-- end header -->

    <!-- products content -->
    <div class="bg-main">
        <div class="container">
            <div class="box">
                <div class="breadcumb">
                    <a href="{% url 'home:index' %}">Trang chủ</a>
                    <span><i class='bx bxs-chevrons-right'></i></span>
                    <a href="{% url 'product:product' %}">Xem tất cả</a>
                </div>
            </div>
            <div class="box">
                <div class="row">
                    <div class="col-3 filter-col" id="filter-col">
                        <div class="box filter-toggle-box">
                            <button class="btn-flat btn-hover" id="filter-close">close</button>
                        </div>
                        <div class="box">
                            <span class="filter-header">
                                Thể loại
                            </span>
                            <ul class="filter-list">
                                {% for category in categories %}
                                    <li><a href="{% url 'product:productfilter' category=category.title %}">{{ category.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- <div class="box">
                            <span class="filter-header">
                                Brands
                            </span>
                            <ul class="filter-list">
                                <li>
                                    <div class="group-checkbox">
                                        <input type="checkbox" id="remember1" checked="checked">
                                        <label for="remember1">
                                            JBL
                                            <i class='bx bx-check'></i>
                                        </label>
                                    </div>
                                </li>
                                <li>
                                    <div class="group-checkbox">
                                        <input type="checkbox" id="remember2">
                                        <label for="remember2">
                                            Beat
                                            <i class='bx bx-check'></i>
                                        </label>
                                    </div>
                                </li>
                                <li>
                                    <div class="group-checkbox">
                                        <input type="checkbox" id="remember3">
                                        <label for="remember3">
                                            Logitech
                                            <i class='bx bx-check'></i>
                                        </label>
                                    </div>
                                </li>
                                <li>
                                    <div class="group-checkbox">
                                        <input type="checkbox" id="remember4">
                                        <label for="remember4">
                                            Samsung
                                            <i class='bx bx-check'></i>
                                        </label>
                                    </div>
                                </li>
                                <li>
                                    <div class="group-checkbox">
                                        <input type="checkbox" id="remember5">
                                        <label for="remember5">
                                            Sony
                                            <i class='bx bx-check'></i>
                                        </label>
                                    </div>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                    <div class="col-9 col-md-12">
                        <!-- <div class="box filter-toggle-box">
                            <button class="btn-flat btn-hover" id="filter-toggle">filter</button>
                        </div> -->
                        <div class="box">
                            <div class="row" id="products">
                                {% for product in products %}
                                <div class="col-3 col-md-6 col-sm-12">
                                    <div class="product-card">
                                        <div class="product-card-img">
                                        <img style="height: 200px; width: 150px; transform: translateX(-7rem);" src="{{ product.image.url }}" alt="">                 
                                         </div>                
                                            <div class="product-card-info">
                                                <div class="product-btn">
                                                <a href="{% url 'product:productdetail' slug=product.slug %}"><button class="btn-flat btn-hover btn-shop-now">Chi tiết</button></a>                                
                                                <a href="" ><button class="btn-flat btn-hover btn-cart-add" id="add-cart-button-product" data-id="{{product.id}}">
                                                    <i class='bx bxs-cart-add'></i>
                                                </button>
                                                </a>
                                                </div>
                                                <div class="product-card-name">
                                                    {{ product.name }}
                                                </div>
                                                <div class="product-card-price">
                                                    <span><del>{{ product.price|floatformat }}</del></span>
                                                    <span class="curr-price">{{ product.price|floatformat }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="box">
                            <ul class="pagination">
                                <li><a href="#"><i class='bx bxs-chevron-left'></i></a></li>
                                <li><a href="#" class="active">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#"><i class='bx bxs-chevron-right'></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end products content -->

    <!-- footer -->
    {% include "base/footer.html" %}
    <!-- end footer -->

    <!-- app js -->
    <script>
        $(document).on('click','#add-cart-button-product', function(e){
            e.preventDefault();
            const product_id = $(this).data("id");
            const quantity =$('#product_quantity').val() || 1;
            $.ajax({
                type:'POST',
                url: '{% url "order:add-to-cart" %}',
                data: {
                    id: product_id,
                    quantity: quantity,
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: "post",
                },
                success: function(json){
                    console.log(json)
                    // document.getElementById("cart-count").innerHTML = json.no_items
                //    $("#AddModal").modal();
                },
                error: function(xhr,errmsg,err){
                    console.log(xhr);
                }
            });
        })
    
     </script>
    <script src="{% static 'home/js/app.js' %}"></script>
    <script>
        let filter_col = document.querySelector('#filter-col')
        document.querySelector('#filter-toggle').addEventListener('click', () => filter_col.classList.toggle('active'))
        document.querySelector('#filter-close').addEventListener('click', () => filter_col.classList.toggle('active'))
    </script>
</body>

</html>