home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'home'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('contact/', Contact.as_view(), name='contact'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('adminpage/', include('adminpage.urls')),
    path('order/', include('order.urls')),
    path('product/', include('product.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'order'

urlpatterns = [
    path('add-to-cart/', AddToCart.as_view(), name='add-to-cart'),
    path('remove_item_in_cart/', RemoveItemToCart.as_view(), name='remove_item_in_cart'),
    path('shopping-cart/', CartView.as_view(), name='cart'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
]

product/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'product'

urlpatterns = [
    path('productdetail/<slug:slug>/', ProductDetail.as_view(), name='productdetail'),
    path('product/', ProductView.as_view(), name='product'),
    path('product/filter/<str:category>', ProductView.as_view(), name='productfilter'),
    path('product/search/', ProductSearch.as_view(), name='productsearch'),
]

order/models.py
from django.db import models
from django.utils.functional import cached_property

from user.models import CustomUser
from product.models import Product


# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    mode = models.IntegerField(default=0, choices=(
        (0, "Chưa đặt"),
        (1, "Đã đặt"),
        (2, "Đã chấp nhận"),
        (3, "Đã nhận hàng"),
    ))
    day_update = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.user}--{self.product}--{self.quantity}"

    @property
    def get_total_price(self):
        return self.quantity * self.product.price

    
class Order(models.Model):
    STATUS_CHOICES = (
        ("OD", "Đặt hàng"),
        ("WFC", "Chờ xác nhận"),
        ("PK", "Đóng gói bàn giao"),
        ('SU', 'Thành công'),
        ('FA', 'Thất bại'),
    )

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="OD")
    created_at = models.DateTimeField(auto_now_add=True)
    total_order = models.IntegerField(default=0)


class OrderDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product")
    price = models.FloatField()
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order')

    @property
    def total_amount(self):
        return self.price * self.quantity

order/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import View
from product.models import Product

from .models import Cart, Order, OrderDetail


# Create your views here.
class CartView(LoginRequiredMixin, View):
    template_name = "order/shopping-cart.html"
    
    def get(self, request, *args, **kwargs):
        carts = Cart.objects.filter(
            user=request.user
        )

        cart_price_total = sum([i.get_total_price for i in carts])

        context = {
            "carts": carts,
            "cart_price_total": cart_price_total,
        }
        return render(request, self.template_name, context)


class PaymentView(LoginRequiredMixin, View):
    template_name = "order/payment.html"
    
    def get(self, request, *args, **kwargs):
        carts = Cart.objects.filter(
            user=request.user)
        cart_price_total = sum([i.get_total_price for i in carts])
        
        context = {
            "carts": carts,
            "cart_price_total": cart_price_total,
        }
            
        return render(request, self.template_name, context)

class CheckOutView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        carts = Cart.objects.filter(
            user=request.user)

        total_price = 0
        order = Order.objects.create(
            user=request.user
        )
        for item in carts:
            total_price += item.get_total_price
            OrderDetail.objects.create(
                product=item.product,
                price=item.product.price,
                quantity=item.quantity,
                order=order
            )
            item.delete()

        order.total_order = total_price
        order.save()
            
        return redirect('home:index')


class AddToCart(LoginRequiredMixin, View):
    template_name = "order/shopping-cart.html"
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        product_id = request.POST.get("id")
        quantity = request.POST.get("quantity")
        product = Product.objects.filter(id=product_id).first()
        carts = Cart.objects.filter(
            user=request.user,
            product=product
        )
        cart = carts.first()

        if cart is None:
            cart = Cart.objects.create(
                user=request.user,
                product=product,
                quantity=quantity
            )
        else:
            cart.quantity = quantity
            cart.save()
        context = {}
        response = JsonResponse(context)
        return response


class RemoveItemToCart(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        id = request.POST.get('id')
        product = Product.objects.filter(id=id).first()
        
        Cart.objects.filter(
            user=request.user,
            product=product,
        ).delete()

        carts = Cart.objects.filter(
            user=request.user
        )

        no_item_in_carts = len(carts)
        cart_price_total = sum([i.get_total_price for i in carts])

        context = {
            "no_item_in_carts": no_item_in_carts,
            "cart_price_total": cart_price_total,
        }
        response = JsonResponse(context)
        return response

order/templates/order/payment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% include "base/head.html" %}
</head>
<body>
    {% include "base/header.html" %}
        <!-- end header -->
        <div class="wrapper-all">
            <!-- header -->
            <!-- title bar box -->
            
            <div class="container">
                <div class="bg-addr">
                    <div class="line-through" style="width: 100%;height: 3px; background-color: #fff;background-position-x: -30px;"></div>
                    <div class="addr-content-payment">
                        <div class="addr-title"><i class="bx bxs-map"></i> Delivery address</div>
                        <div class="addr-content-i4" style="display: flex;">
                            <div class="addr-detail" style="text-transform: uppercase;">Hong Vinh Dat (+84) 384173970</div>
                            <div class="addr-detail-addr" style="font-size: 16px;">27/1/9 Đường số 9 , Phường 16 , Quận Gò Vấp, Phường 16 ,TP.Hồ Chí Minh</div>
                            <div class="addr-default">Default</div>
                            <div class="addr-change"style="text-transform: uppercase;"> <a href="#">Change</a></div>
                        </div>
                    </div>
                </div>

                <div class="box-order">
                    <div class="box-order-product-name">Sản phẩm</div>
                    <div class="box-order-product-categories w-auto">Thể loại</div>
                    <div class="box-order-price w-auto">Giá</div>
                    <div class="box-order-quantity w-auto">Số lượng</div>
                    <div class="box-order-total w-auto">Thành tiền</div>
                </div>
            </div>
            <!-- end title bar box -->


            <!-- begin detail shopping cart -->
            
            <div class="container">
                <div class="shopping-cart-detail-box">
                    <div class="inline-box">
                        <div class="inline-favorite-brand">Mall</div>
                        <div class="inline-shop-name">LDStore</div>
                        <div class="inline-mess">Chat Now</div>
                    </div>
                    {% for item in carts %}
                    <div class="product-shopping-cart-card">
                        <div class="wrap-checkbox-img">
                            <div class="product-cart-img" style="background-image: url({{item.product.image.url}});">
                            </div>
                            <div class="product-cart-name"><a href="#">{{ item.product.name|truncatechars:12 }}</a></div>
                        </div>
                        <div class="product-cart-categories">{{ item.product.category }}</div>
                        <div class="product-cart-price">
                            <!-- <div class="product-cart-old-price">60.000Đ</div> -->
                            <div class="product-cart-old-new-price">{{ item.product.price }}Đ</div>
                        </div>
                        <div class="product-cart-quantity">
                            <div class="product-quantity-wrapper">
                                <span class="product-quantity-btn-minus">
                                    <i class="bx bx-minus"></i>
                                </span>
                                <input type="text" value="{{ item.quantity }}" class="product-quantity"></input>
                                <span class="product-quantity-btn-plus">
                                    <i class="bx bx-plus"></i>
                                </span>
                            </div>
                        </div>
                        <div class="product-cart-total">{{ item.get_total_price }}Đ</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- end detail shopping cart -->
            <div class="container">
                <div class="payment-cart-voucher">
                    <div class="payment-cart-voucher-title">Shop's voucher</div>
                    <div class="payment-cart-voucher-choose">
                        <a href="#">Choose voucher</a>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="wrapper-note-box">
                    <div class="note-box">
                        <div class="note-box-message">Message:</div>
                        <div class="note-box-message-shop"><input type="text" name="" id="" placeholder="Luu y cho nguoi ban...."></div>
                    </div>
                    <div class="note-shipping-option">
                        <div class="note-shipping-title">shipping options:</div>
                        <div class="note-shipping-name">
                            <div class="note-shipping-name-detail-1">Van chuyen nhanh quoc te</div>
                            <div class="note-shipping-name-detail-2">Standard Express</div>
                            <div class="note-shipping-name-detail-3">Nhan hang vao 21th04 - 12th05</div>
                            <div class="note-shipping-name-detail-4">(Do anh huong boi Covid19 , thoi gian giao hang quoc te co the keo dai hon du kien)</div>
                        </div>
                        <div class="note-shipping-change">Change</div>
                        <div class="note-shipping-price">21.000Đ</div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="note-shipping-order-total">
                    <div class="order-total-text">order total({% if carts %}{{ carts|length }}{% else %}0{% endif %} items):</div>
                    <div class="order-total-price">{{ cart_price_total }}Đ</div>
                </div>
            </div>
            <div class="container">
                <div class="payment-method">
                    <div class="payment-method-title">payment method</div>
                    <button class="payment-method-button1">Credit Cards</button>
                    <button class="payment-method-button-2" data-modal-target="#modal">Cash on delivery</button>
                </div>
                <div class="wrap-payment-detail-content">
                    <div class="line1-payment" style="display: flex;">
                        <div class="l1-dt">
                            Thanh toán khi nhận hàng
                        </div>
                        <div class="l1-dt-1">
                            Phí thu hộ: ₫0 VNĐ. Ưu đãi về phí vận chuyển (nếu có) áp dụng cả với phí thu hộ.
                        </div>
                    </div>
                    <div class="line2-payment">
                        <div class="l2-dt-1" style="display: flex;">Tổng tiền hàng
                            <div class="l2-dt-1-1">₫{{ cart_price_total }}</div>
                        </div>
                        <div class="l2-dt-2"style="display: flex;">Phí vận chuyển
    
                            <div class="l2-dt-2-1">₫21.000</div>
                        </div>
                        <div class="l2-dt-3"style="display: flex;">Tổng thanh toán:
    
                            <div class="l2-dt-3-1">₫{{ cart_price_total }}</div>
                        </div>
                    </div>
                    <div class="line3-payment" style="display: flex;">
                        <div class="line3-content-1">Nhấn "Đặt hàng" đồng nghĩa với việc bạn đồng ý tuân theo Điều khoản LDstore</div>
                        <div class="wrap-buy-btn-payment">
                            <div class="buy-btn-cart "style="width:170px"><a href='{% url "order:checkout" %}'>Đặt Hàng</a></div>
                        </div>
                    </div>

                </div>
                
            </div>
        </div>
        
        {% include "base/footer.html" %}
        <script src="{% static 'home/js/app.js' %}"></script>
        <script src="{% static 'product/js/product-detail.js' %}"></script>
    </body>

order/templates/order/shopping-cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% include "base/head.html" %}
</head>
<body>
    {% include "base/header.html" %}

    <div class="wrapper-all">
            <!-- header -->

            <!-- title bar box -->

            <div class="container">
                <div class="box-order">
                    <div class="checkbox-custom">
                        <!-- <input type="checkbox"></input> -->
                    </div>
                    <div class="box-order-product-name">Sản phẩm</div>
                    <div class="box-order-product-categories">Thể loại</div>
                    <div class="box-order-price">Giá</div>
                    <div class="box-order-quantity">Số lượng</div>
                    <div class="box-order-total">Thành tiền</div>
                    <div class="box-order-actions">Thao tác</div>
                </div>
            </div>
            <!-- end title bar box -->

            <!-- begin shop name -->

            <div class="container">
                <div class="shop-name-box">
                    <div class="checkbox-custom">
                        <!-- <input type="checkbox"></input> -->
                    </div>
                    <div class="shop-name-cart">LDStore</div>
                </div>
            </div>
            <!-- end shop name -->

            <!-- begin detail shopping cart -->
            <div class="container" id="table-cart">
                {% for item in carts %}
                <div class="shopping-cart-detail-box">
                    <div class="product-shopping-cart-card">
                        <div class="wrap-checkbox-img">
                            <div class="checkbox-custom">
                                <!-- <input type="checkbox"></input> -->
                            </div>
                            <div class="product-cart-img" style="background-image: url({{item.product.image.url}});">
                            </div>
                            <div class="product-cart-name"><a href="{% url 'product:productdetail' slug=item.product.slug %}">{{ item.product.name|truncatechars:12 }}</a></div>
                        </div>
                        <div class="product-cart-categories">{{ item.product.category }}</div>
                        <div class="product-cart-price">
                            <!-- <div class="product-cart-old-price">60.000Đ</div> -->
                            <div class="product-cart-old-new-price">{{ item.product.price }}Đ</div>
                        </div>
                        <div class="product-cart-quantity">
                            <div class="product-quantity-wrapper">
                                <span class="product-quantity-btn-minus">
                                    <i class="bx bx-minus"></i>
                                </span>
                                <input type="text" value="{{ item.quantity }}" class="product-quantity"></input>
                                <span class="product-quantity-btn-plus">
                                    <i class="bx bx-plus"></i>
                                </span>
                            </div>
                        </div>
                        <div class="product-cart-total">{{ item.get_total_price }}Đ</div>
                        <div class="product-cart-actions">
                            <a id="remove_item_in_cart" data-product-id ={{ item.product.id }}>
                                Xóa
                            </a></div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- end detail shopping cart -->
            <div class="container">
                <div class="payment-cart">
                    <div class="shop-name-box">
                        <div class="checkbox-custom">
                            
                        </div>
                        <div class="payment-quantity" style="font-weight: 500;">
                               
                        </div>
                    </div>
                    <div class="voucher">LDStore voucher</div>
                    <div class="payment-total" id="payment-total">Tổng thanh toán ({% if carts %}{{ carts|length }}{% else %}0{% endif %}) sản phẩm</div>
                    <div class="payment-price" id="payment-price">{{ cart_price_total }}Đ</div>
                    <div class="buy-btn-cart"><a href='{% url "order:payment" %}'>Mua hàng</a></div>
                </div>

            </div>
            <!-- footer -->
            <!-- end footer -->
            <!-- line-between -->

        </div>
        
        {% include "base/footer.html" %}
        <script src="{% static 'home/js/app.js' %}"></script>
        <script src="{% static 'product/js/product-detail.js' %}"></script>
    </body>
    <script>
        $(document).on('click','#remove_item_in_cart', function(e){
       e.preventDefault();
       const id =$('#remove_item_in_cart').attr('data-product-id');
       $.ajax({
           type:'POST',
           url: '{% url "order:remove_item_in_cart" %}',
           data: {
               id: id,
               csrfmiddlewaretoken: "{{csrf_token}}",
               action: "post",
           },
           success: function(json){
               console.log(json)
               $('#table-cart').load(' #table-cart');
               document.getElementById('payment-total').innerHTML = `Tổng thanh toán (${json.no_item_in_carts}) sản phẩm`;
               document.getElementById('payment-price').innerHTML = `${json.cart_price_total}Đ`;
           },
           error: function(xhr,errmsg,err){
               console.log(xhr);
           }
        });
    })
    </script>